channels:
  - manics
  - conda-forge
  - defaults
dependencies:
  - websockify
  - libglu
  - glew
  - mesalib
  - pandasgui
  - pandas
  - pip
  - pip:
    - .
    - xvfbwrapper
    - PyOpenGL
    - PyOpenGL_accelerate

    
